version: '3.4'

services:
  temperaturapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 5000:80

  temperaturdatabase:
    image: mcr.microsoft.com/mssql/server
    container_name: temperaturdatabase
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Passw0rd123!